### ISSUE TITLE
Getting bit size from IPv4Subnet

### ISSUE THREAD

**Issue by heschong** [ip-num/ip-num#40]
```(new IPv4SubnetMask('255.255.0.0')).prefix``` 

This should equal 16 (since 255.255.0.0 is a /16) but the code above returns 32 (no matter what net mask is provided). Is there a better way to get the correct bit size? This is using version 1.2.2

**Comment by dadepo** [comment]
Hi @heschong 

There is no `prefix` method on `IPv4SubnetMask`. I assume you are referring to `bitSize`? And yes that will always be 32 because it returns the number of bits needed to represents the value of the IP number.

But I think having a `prefix` method would be handy so I will note this down and include is as part of 1.3.0 which I am currently working on.
